//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Expenses", "FK_dbo_Projects_dbo_Clients_ClientID", "Clients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Expenses.Clients), "Projects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Expenses.Projects), true)]
[assembly: EdmRelationshipAttribute("Expenses", "FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "Reports", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Expenses.Reports), "ExpenseDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Expenses.ExpenseDetails), true)]
[assembly: EdmRelationshipAttribute("Expenses", "FK_dbo_Reports_dbo_Projects_ProjectID", "Projects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Expenses.Projects), "Reports", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Expenses.Reports), true)]

#endregion

namespace Expenses
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExpensesContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExpensesContext object using the connection string found in the 'ExpensesContext' section of the application configuration file.
        /// </summary>
        public ExpensesContext() : base("name=ExpensesContext", "ExpensesContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpensesContext object.
        /// </summary>
        public ExpensesContext(string connectionString) : base(connectionString, "ExpensesContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpensesContext object.
        /// </summary>
        public ExpensesContext(EntityConnection connection) : base(connection, "ExpensesContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C__MigrationHistory> C__MigrationHistory
        {
            get
            {
                if ((_C__MigrationHistory == null))
                {
                    _C__MigrationHistory = base.CreateObjectSet<C__MigrationHistory>("C__MigrationHistory");
                }
                return _C__MigrationHistory;
            }
        }
        private ObjectSet<C__MigrationHistory> _C__MigrationHistory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clients> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Clients>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Clients> _Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Establishments> Establishments
        {
            get
            {
                if ((_Establishments == null))
                {
                    _Establishments = base.CreateObjectSet<Establishments>("Establishments");
                }
                return _Establishments;
            }
        }
        private ObjectSet<Establishments> _Establishments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExpenseDetails> ExpenseDetails
        {
            get
            {
                if ((_ExpenseDetails == null))
                {
                    _ExpenseDetails = base.CreateObjectSet<ExpenseDetails>("ExpenseDetails");
                }
                return _ExpenseDetails;
            }
        }
        private ObjectSet<ExpenseDetails> _ExpenseDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Projects> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Projects>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Projects> _Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reports> Reports
        {
            get
            {
                if ((_Reports == null))
                {
                    _Reports = base.CreateObjectSet<Reports>("Reports");
                }
                return _Reports;
            }
        }
        private ObjectSet<Reports> _Reports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C__MigrationHistory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC__MigrationHistory(C__MigrationHistory c__MigrationHistory)
        {
            base.AddObject("C__MigrationHistory", c__MigrationHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Clients clients)
        {
            base.AddObject("Clients", clients);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Establishments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstablishments(Establishments establishments)
        {
            base.AddObject("Establishments", establishments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExpenseDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExpenseDetails(ExpenseDetails expenseDetails)
        {
            base.AddObject("ExpenseDetails", expenseDetails);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Projects projects)
        {
            base.AddObject("Projects", projects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReports(Reports reports)
        {
            base.AddObject("Reports", reports);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Expenses", Name="C__MigrationHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C__MigrationHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C__MigrationHistory object.
        /// </summary>
        /// <param name="migrationId">Initial value of the MigrationId property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="productVersion">Initial value of the ProductVersion property.</param>
        public static C__MigrationHistory CreateC__MigrationHistory(global::System.String migrationId, global::System.Byte[] model, global::System.String productVersion)
        {
            C__MigrationHistory c__MigrationHistory = new C__MigrationHistory();
            c__MigrationHistory.MigrationId = migrationId;
            c__MigrationHistory.Model = model;
            c__MigrationHistory.ProductVersion = productVersion;
            return c__MigrationHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MigrationId
        {
            get
            {
                return _MigrationId;
            }
            set
            {
                if (_MigrationId != value)
                {
                    OnMigrationIdChanging(value);
                    ReportPropertyChanging("MigrationId");
                    _MigrationId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MigrationId");
                    OnMigrationIdChanged();
                }
            }
        }
        private global::System.String _MigrationId;
        partial void OnMigrationIdChanging(global::System.String value);
        partial void OnMigrationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Model
        {
            get
            {
                return StructuralObject.GetValidValue(_Model);
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.Byte[] _Model;
        partial void OnModelChanging(global::System.Byte[] value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductVersion
        {
            get
            {
                return _ProductVersion;
            }
            set
            {
                OnProductVersionChanging(value);
                ReportPropertyChanging("ProductVersion");
                _ProductVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductVersion");
                OnProductVersionChanged();
            }
        }
        private global::System.String _ProductVersion;
        partial void OnProductVersionChanging(global::System.String value);
        partial void OnProductVersionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Expenses", Name="Clients")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clients : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clients object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        public static Clients CreateClients(global::System.Int32 id, global::System.String clientName)
        {
            Clients clients = new Clients();
            clients.Id = id;
            clients.ClientName = clientName;
            return clients;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Expenses", "FK_dbo_Projects_dbo_Clients_ClientID", "Projects")]
        public EntityCollection<Projects> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Projects>("Expenses.FK_dbo_Projects_dbo_Clients_ClientID", "Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Projects>("Expenses.FK_dbo_Projects_dbo_Clients_ClientID", "Projects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Expenses", Name="Establishments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Establishments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Establishments object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="establishmentName">Initial value of the EstablishmentName property.</param>
        public static Establishments CreateEstablishments(global::System.Int32 id, global::System.String establishmentName)
        {
            Establishments establishments = new Establishments();
            establishments.Id = id;
            establishments.EstablishmentName = establishmentName;
            return establishments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EstablishmentName
        {
            get
            {
                return _EstablishmentName;
            }
            set
            {
                OnEstablishmentNameChanging(value);
                ReportPropertyChanging("EstablishmentName");
                _EstablishmentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EstablishmentName");
                OnEstablishmentNameChanged();
            }
        }
        private global::System.String _EstablishmentName;
        partial void OnEstablishmentNameChanging(global::System.String value);
        partial void OnEstablishmentNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Expenses", Name="ExpenseDetails")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExpenseDetails : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExpenseDetails object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateIncurred">Initial value of the DateIncurred property.</param>
        /// <param name="numberOfGuest">Initial value of the NumberOfGuest property.</param>
        /// <param name="extablishment">Initial value of the Extablishment property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="amountPerPerson">Initial value of the AmountPerPerson property.</param>
        /// <param name="reportId">Initial value of the ReportId property.</param>
        public static ExpenseDetails CreateExpenseDetails(global::System.Int32 id, global::System.DateTime dateIncurred, global::System.Int32 numberOfGuest, global::System.String extablishment, global::System.Double amount, global::System.Double amountPerPerson, global::System.Int32 reportId)
        {
            ExpenseDetails expenseDetails = new ExpenseDetails();
            expenseDetails.Id = id;
            expenseDetails.DateIncurred = dateIncurred;
            expenseDetails.NumberOfGuest = numberOfGuest;
            expenseDetails.Extablishment = extablishment;
            expenseDetails.Amount = amount;
            expenseDetails.AmountPerPerson = amountPerPerson;
            expenseDetails.ReportId = reportId;
            return expenseDetails;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReceiptEntry
        {
            get
            {
                return _ReceiptEntry;
            }
            set
            {
                OnReceiptEntryChanging(value);
                ReportPropertyChanging("ReceiptEntry");
                _ReceiptEntry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReceiptEntry");
                OnReceiptEntryChanged();
            }
        }
        private global::System.String _ReceiptEntry;
        partial void OnReceiptEntryChanging(global::System.String value);
        partial void OnReceiptEntryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateIncurred
        {
            get
            {
                return _DateIncurred;
            }
            set
            {
                OnDateIncurredChanging(value);
                ReportPropertyChanging("DateIncurred");
                _DateIncurred = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateIncurred");
                OnDateIncurredChanged();
            }
        }
        private global::System.DateTime _DateIncurred;
        partial void OnDateIncurredChanging(global::System.DateTime value);
        partial void OnDateIncurredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumberOfGuest
        {
            get
            {
                return _NumberOfGuest;
            }
            set
            {
                OnNumberOfGuestChanging(value);
                ReportPropertyChanging("NumberOfGuest");
                _NumberOfGuest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfGuest");
                OnNumberOfGuestChanged();
            }
        }
        private global::System.Int32 _NumberOfGuest;
        partial void OnNumberOfGuestChanging(global::System.Int32 value);
        partial void OnNumberOfGuestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuestNames
        {
            get
            {
                return _GuestNames;
            }
            set
            {
                OnGuestNamesChanging(value);
                ReportPropertyChanging("GuestNames");
                _GuestNames = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuestNames");
                OnGuestNamesChanged();
            }
        }
        private global::System.String _GuestNames;
        partial void OnGuestNamesChanging(global::System.String value);
        partial void OnGuestNamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Extablishment
        {
            get
            {
                return _Extablishment;
            }
            set
            {
                OnExtablishmentChanging(value);
                ReportPropertyChanging("Extablishment");
                _Extablishment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Extablishment");
                OnExtablishmentChanged();
            }
        }
        private global::System.String _Extablishment;
        partial void OnExtablishmentChanging(global::System.String value);
        partial void OnExtablishmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expensecategory
        {
            get
            {
                return _Expensecategory;
            }
            set
            {
                OnExpensecategoryChanging(value);
                ReportPropertyChanging("Expensecategory");
                _Expensecategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expensecategory");
                OnExpensecategoryChanged();
            }
        }
        private global::System.String _Expensecategory;
        partial void OnExpensecategoryChanging(global::System.String value);
        partial void OnExpensecategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Double _Amount;
        partial void OnAmountChanging(global::System.Double value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AmountPerPerson
        {
            get
            {
                return _AmountPerPerson;
            }
            set
            {
                OnAmountPerPersonChanging(value);
                ReportPropertyChanging("AmountPerPerson");
                _AmountPerPerson = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AmountPerPerson");
                OnAmountPerPersonChanged();
            }
        }
        private global::System.Double _AmountPerPerson;
        partial void OnAmountPerPersonChanging(global::System.Double value);
        partial void OnAmountPerPersonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReportId
        {
            get
            {
                return _ReportId;
            }
            set
            {
                OnReportIdChanging(value);
                ReportPropertyChanging("ReportId");
                _ReportId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportId");
                OnReportIdChanged();
            }
        }
        private global::System.Int32 _ReportId;
        partial void OnReportIdChanging(global::System.Int32 value);
        partial void OnReportIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Expenses", "FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "Reports")]
        public Reports Reports
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reports>("Expenses.FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "Reports").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reports>("Expenses.FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "Reports").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reports> ReportsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reports>("Expenses.FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "Reports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reports>("Expenses.FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "Reports", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Expenses", Name="Projects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Projects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Projects object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="projectName">Initial value of the ProjectName property.</param>
        public static Projects CreateProjects(global::System.Int32 id, global::System.Int32 clientId, global::System.String projectName)
        {
            Projects projects = new Projects();
            projects.Id = id;
            projects.ClientId = clientId;
            projects.ProjectName = projectName;
            return projects;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProjectName
        {
            get
            {
                return _ProjectName;
            }
            set
            {
                OnProjectNameChanging(value);
                ReportPropertyChanging("ProjectName");
                _ProjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProjectName");
                OnProjectNameChanged();
            }
        }
        private global::System.String _ProjectName;
        partial void OnProjectNameChanging(global::System.String value);
        partial void OnProjectNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Expenses", "FK_dbo_Projects_dbo_Clients_ClientID", "Clients")]
        public Clients Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("Expenses.FK_dbo_Projects_dbo_Clients_ClientID", "Clients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("Expenses.FK_dbo_Projects_dbo_Clients_ClientID", "Clients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clients> ClientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("Expenses.FK_dbo_Projects_dbo_Clients_ClientID", "Clients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clients>("Expenses.FK_dbo_Projects_dbo_Clients_ClientID", "Clients", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Expenses", "FK_dbo_Reports_dbo_Projects_ProjectID", "Reports")]
        public EntityCollection<Reports> Reports
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reports>("Expenses.FK_dbo_Reports_dbo_Projects_ProjectID", "Reports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reports>("Expenses.FK_dbo_Reports_dbo_Projects_ProjectID", "Reports", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Expenses", Name="Reports")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reports : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reports object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="monthYear">Initial value of the MonthYear property.</param>
        /// <param name="billable">Initial value of the Billable property.</param>
        /// <param name="empName">Initial value of the EmpName property.</param>
        /// <param name="empTitle">Initial value of the EmpTitle property.</param>
        /// <param name="projectID">Initial value of the ProjectID property.</param>
        public static Reports CreateReports(global::System.Int32 id, global::System.DateTime monthYear, global::System.Boolean billable, global::System.String empName, global::System.String empTitle, global::System.Int32 projectID)
        {
            Reports reports = new Reports();
            reports.Id = id;
            reports.MonthYear = monthYear;
            reports.Billable = billable;
            reports.EmpName = empName;
            reports.EmpTitle = empTitle;
            reports.ProjectID = projectID;
            return reports;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MonthYear
        {
            get
            {
                return _MonthYear;
            }
            set
            {
                OnMonthYearChanging(value);
                ReportPropertyChanging("MonthYear");
                _MonthYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MonthYear");
                OnMonthYearChanged();
            }
        }
        private global::System.DateTime _MonthYear;
        partial void OnMonthYearChanging(global::System.DateTime value);
        partial void OnMonthYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ErNumber
        {
            get
            {
                return _ErNumber;
            }
            set
            {
                OnErNumberChanging(value);
                ReportPropertyChanging("ErNumber");
                _ErNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErNumber");
                OnErNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ErNumber;
        partial void OnErNumberChanging(Nullable<global::System.Int32> value);
        partial void OnErNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Billable
        {
            get
            {
                return _Billable;
            }
            set
            {
                OnBillableChanging(value);
                ReportPropertyChanging("Billable");
                _Billable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Billable");
                OnBillableChanged();
            }
        }
        private global::System.Boolean _Billable;
        partial void OnBillableChanging(global::System.Boolean value);
        partial void OnBillableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpName
        {
            get
            {
                return _EmpName;
            }
            set
            {
                OnEmpNameChanging(value);
                ReportPropertyChanging("EmpName");
                _EmpName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpName");
                OnEmpNameChanged();
            }
        }
        private global::System.String _EmpName;
        partial void OnEmpNameChanging(global::System.String value);
        partial void OnEmpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpTitle
        {
            get
            {
                return _EmpTitle;
            }
            set
            {
                OnEmpTitleChanging(value);
                ReportPropertyChanging("EmpTitle");
                _EmpTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpTitle");
                OnEmpTitleChanged();
            }
        }
        private global::System.String _EmpTitle;
        partial void OnEmpTitleChanging(global::System.String value);
        partial void OnEmpTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                OnProjectIDChanging(value);
                ReportPropertyChanging("ProjectID");
                _ProjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectID");
                OnProjectIDChanged();
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Expenses", "FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "ExpenseDetails")]
        public EntityCollection<ExpenseDetails> ExpenseDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExpenseDetails>("Expenses.FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "ExpenseDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExpenseDetails>("Expenses.FK_dbo_ExpenseDetails_dbo_Reports_ReportId", "ExpenseDetails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Expenses", "FK_dbo_Reports_dbo_Projects_ProjectID", "Projects")]
        public Projects Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projects>("Expenses.FK_dbo_Reports_dbo_Projects_ProjectID", "Projects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projects>("Expenses.FK_dbo_Reports_dbo_Projects_ProjectID", "Projects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Projects> ProjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Projects>("Expenses.FK_dbo_Reports_dbo_Projects_ProjectID", "Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Projects>("Expenses.FK_dbo_Reports_dbo_Projects_ProjectID", "Projects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Expenses", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
